drop DATABASE BMS_DB;
Create database BMS_DB1;
use BMS_DB1;

SHOW databases;

-- CUSTOMER_PERSONAL_INFO

CREATE TABLE CUSTOMER_PERSONAL_INFO
(
CUSTOMER_ID varchar(5),
CUSTOMER_NAME varchar(30),
DATE_OF_BIRTH DATE,
GUARDIAN_NAME varchar(30),
ADDRESS varchar(50),
CONTACT_NO bigint(10),
MAIL_ID varchar(30),
GENDER CHAR(1),
MARITAL_STATUS varchar(10),
IDENTIFICATION_DOC_TYPE varchar(20),
ID_DOC_NO varchar(20),
CITIZENSHIP varchar(10),
primary key (CUSTOMER_id)
);
DROP TABLE CUSTOMER_REFERENCE_INFO;
SELECT * FROM CUSTOMER_PERSONAL_INFO;
SHOW TABLES;

-- CUSTOMER REFERENCE TABLE

CREATE TABLE CUSTOMER_REFERENCE_INFO 
(
CUSTOMER_ID varchar(5),
REFERENCE_ACC_NAME varchar(20),
REFERENCE_ACC_NO bigint(16),
REFERENCE_ACC_ADDRESS VARCHAR(50),
RELATION VARCHAR(25),
primary key(CUSTOMER_ID),
foreign key(CUSTOMER_ID) references CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);

-- BANK_INFO

CREATE TABLE BANK_INFO
(
IFSC_CODE varchar(15),
BANK_NAME varchar(25),
BRANCH_NAME VARCHAR(25),
primary key(IFSC_CODE)
);

-- ACCOUNT_INFO

CREATE TABLE ACCOUNT_INFO 
(
ACCOUNT_NO BIGINT(16),
CUSTOMER_ID VARCHAR(5),
ACCOUNT_TYPE VARCHAR(10),
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
IFSC_CODE VARCHAR(10),
INTEREST DECIMAL(7,2),
INITIAL_DEPOSIT BIGINT(10),
primary key(ACCOUNT_NO),
foreign key(CUSTOMER_ID) REFERENCES CUSTOMER_REFERENCE_INFO(CUSTOMER_ID),
foreign key(IFSC_CODE) references BANK_INFO(IFSC_CODE)
);

-- BANK_INFO

INSERT INTO BANK_INFO VALUES('HDV001', 'SBI', 'SHAKTI NAGAR');

INSERT INTO BANK_INFO VALUES('SDW002', 'SBI', 'SUBHASH NAGAR');
INSERT INTO BANK_INFO VALUES('LKJ002', 'HDFC', 'ROHINI');
INSERT INTO BANK_INFO VALUES('MXB988', 'ICICI', 'PUNJABI BAGH');
INSERT INTO BANK_INFO VALUES('AHH351', 'KOTAK', 'SHADHARA');
INSERT INTO BANK_INFO VALUES('LOO866', 'PNB', 'TILAK NAGAR');

select * FROM BANK_INFO;

-- CUSTOMER_PERSONAL_INFO

INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C01', 'ALI', '2000-4-24', 'RAVI', 'ROHINI', 9999236108, 'firstperson@bank.com', 'M', 'Married' , 'aadhar', '27829937', 'Indian' );

INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C02', 'BALI', '2000-5-28', 'AVI', 'ROHINI WEST', 9999236109, 'scndperson@bank.com', 'F', 'Married' , 'aadhar', '27888937', 'PAKISTANI' );
INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C03', 'CALI', '2000-8-21', 'BAVI', 'ROHINI EAST', 9999236890, 'thirdperson@bank.com', 'M', 'UNMarried' , 'PASSPORT', '99929937', 'AMERICAN' );
INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C04', 'DALI', '2000-9-14', 'CHAVI', 'ROHINI SOUTH', 9999287908, 'fourthperson@bank.com', 'F', 'Married' , 'aadhar', '20239937', 'SERBIAN' );
INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C05', 'EALI', '2000-10-04', 'MAVI', 'ROHINI NORTH', 9769236108, 'fifthperson@bank.com', 'M', 'UNMarried' , 'DL', '27826547', 'Indian' );
select * FRom CUSTOMER_PERSONAL_INFO;


 

